<?php
// $Id: template.php,v 1.4.2.1 2007/04/18 03:38:59 drumm Exp $

/**
 * Sets the body-tag class attribute.
 *
 * Adds 'sidebar-left', 'sidebar-right' or 'sidebars' classes as needed.
 */
function phptemplate_body_class($sidebar_left, $sidebar_right) {
  if ($sidebar_left != '' && $sidebar_right != '') {
    $class = 'sidebars';
  }
  else {
    if ($sidebar_left != '') {
      $class = 'sidebar-left';
    }
    if ($sidebar_right != '') {
      $class = 'sidebar-right';
    }
  }

  if (isset($class)) {
    print ' class="'. $class .'"';
  }
}

/**
 * Return a themed breadcrumb trail.
 *
 * @param $breadcrumb
 *   An array containing the breadcrumb links.
 * @return a string containing the breadcrumb output.
 */
function phptemplate_breadcrumb($breadcrumb) {
  if (!empty($breadcrumb)) {
    return '<div class="breadcrumb">'. implode(' › ', $breadcrumb) .'</div>';
  }
}

/**
 * Allow themable wrapping of all comments.
 */
function phptemplate_comment_wrapper($content, $type = null) {
  static $node_type;
  if (isset($type)) $node_type = $type;

  if (!$content || $node_type == 'forum') {
    return '<div id="comments">'. $content . '</div>';
  }
  else {
    return '<div id="comments"><h2 class="comments">'. t('Comments') .'</h2>'. $content .'</div>';
  }
}

/**
 * Override or insert PHPTemplate variables into the templates.
 */
function _phptemplate_variables($hook, $vars) {
  if ($hook == 'page') {

    if ($secondary = menu_secondary_local_tasks()) {
      $output = '<span class="clear"></span>';
      $output .= "<ul class=\"tabs secondary\">\n". $secondary ."</ul>\n";
      $vars['tabs2'] = $output;
    }

    // Hook into color.module
    if (module_exists('color')) {
      _color_page_alter($vars);
    }
    return $vars;
  }
  return array();
}

/**
 * Returns the rendered local tasks. The default implementation renders
 * them as tabs.
 *
 * @ingroup themeable
 */
function phptemplate_menu_local_tasks() {
  $output = '';

  if ($primary = menu_primary_local_tasks()) {
    $output .= "<ul class=\"tabs primary\">\n". $primary ."</ul>\n";
  }

  return $output;
}

/**
   * This snippet catches the default login form and looks for an
   * user_login.tpl.php file in the theme folder
   */
/**
 * Aca le decimos a Drupal que queremos invocar a otro archivo cuando llame a user_login
 * El archivo que vamos a usar el user_login.tpl.php
 * */
function phptemplate_user_login($form) {
    return _phptemplate_callback('user_login', array('form' => $form));
}

/*
 * Lo mismo en este caso, aca le decimos que queremos cargar el user_register.tpl.php para hacer el formulario de registro 
 **/
function phptemplate_user_register($form) {
    return _phptemplate_callback('user_register', array('form' => $form));
}

/*
 * Lo mismo en este caso, aca le decimos que queremos cargar el user_register.tpl.php para hacer el formulario de registro 
 **/
function phptemplate_user_edit($form) {
    return _phptemplate_callback('user_edit', array('form' => $form));
}

function phptemplate_user_pass($user, $form = array(), $form1 = array()) {
  // Display form:
  $form['name'] = array('#type' => 'textfield',
    '#title' => t('Username or e-mail address'),
    '#size' => 60,
    '#maxlength' => max(USERNAME_MAX_LENGTH, EMAIL_MAX_LENGTH),
    '#required' => TRUE,
  );
  $form['submit'] = array('#type' => 'submit',
    '#value' => t('E-mail new password'),
    '#weight' => 2,
  );
  
  $form['submit_login'] = array('#type' => 'submit', '#value' => t('Log in'), '#weight' => 2, '#attributes' => array('tabindex' => '3'));

  return _phptemplate_callback('user_pass', array('form' => $form));
}

/**
 * views template to output a view.
 * This code was generated by the views theming wizard
 * Date: Mon, 08/03/2010 - 16:25
 * View: mi_educacion
 *
 * This function goes in your template.php file
 */
function phptemplate_views_view_list_mi_educacion($view, $nodes, $type) {
  $fields = _views_get_fields();

  $taken = array();

  // Set up the fields in nicely named chunks.
  foreach ($view->field as $id => $field) {
    $field_name = $field['field'];
    if (isset($taken[$field_name])) {
      $field_name = $field['queryname'];
    }
    $taken[$field_name] = true;
    $field_names[$id] = $field_name;
  }

  // Set up some variables that won't change.
  $base_vars = array(
    'view' => $view,
    'view_type' => $type,
  );

  foreach ($nodes as $i => $node) {
    $vars = $base_vars;
    $vars['node'] = $node;
    $vars['count'] = $i;
    $vars['stripe'] = $i % 2 ? 'even' : 'odd';
    foreach ($view->field as $id => $field) {
      $name = $field_names[$id];
      $vars[$name] = views_theme_field('views_handle_field', $field['queryname'], $fields, $field, $node, $view);
      if (isset($field['label'])) {
        $vars[$name . '_label'] = $field['label'];
      }
    }
    $items[] = _phptemplate_callback('views-list-mi_educacion', $vars);
  }
  if ($items) {
    return theme('item_list', $items);
  }
}

/*
function phptemplate_node_form($form) {
  $output = '';
  $output .= drupal_render($form['title']);
  $output .= drupal_render($form['body_filter']);
  $output .= drupal_render($form['taxonomy'][6]);
  //$output .= drupal_render($form); // Process any other fields and display them
  return $output;
}*/
  
function custom_p_educacion() {
return drupal_get_form('custom_p_educacion_form');
}
function custom_p_educacion_form() {
	$form['title'] = array(
		'#type'  => 'textfield',
		'#title' => 'Titulo',
		);
		
	$form['educacion']['asociar'] = array(
    	'#type' => 'fieldset',
    	'#title' => t('Datos del instituto'),
    	'#collapsible' => FALSE,
    	'#collapsed' => FALSE,
    	'#weight' => 0,
    	'#parents' => array('publicador'),
	);
		
	$instituto = taxonomy_form(6);
	$form['educacion']['taxonomy[6]'] = array(
    	'#type' => 'select', 
    	'#title' => t($instituto["#title"]), 
    	'#default_value' => $instituto["#default_value"], 
    	'#options' => $instituto["#options"],
		//'#parents' => array('publicador'),
	);
		
	$instituto = taxonomy_form(5);
	$form['educacion']['taxonomy[5]'] = array(
    	'#type' => 'select', 
    	'#title' => t($instituto["#title"]), 
    	'#default_value' => $instituto["#default_value"], 
    	'#options' => $instituto["#options"],
		//'#parents' => array('publicador'),
	);
		
	$instituto = taxonomy_form(3);
	$form['educacion']['taxonomy[3]'] = array(
    	'#type' => 'select', 
    	'#title' => t($instituto["#title"]), 
    	'#default_value' => $instituto["#default_value"], 
    	'#options' => $instituto["#options"],
		//'#parents' => array('publicador'),
	);
		
	$instituto = taxonomy_form(4);
	$form['educacion']['taxonomy[4]'] = array(
    	'#type' => 'select', 
    	'#title' => t($instituto["#title"]), 
    	'#default_value' => $instituto["#default_value"], 
    	'#options' => $instituto["#options"],
		//'#parents' => array('publicador'),
	);
		
	$instituto = taxonomy_form(7);
	$form['taxonomy[7]'] = array(
    	'#type' => 'select', 
    	'#title' => t($instituto["#title"]), 
    	'#default_value' => $instituto["#default_value"], 
    	'#options' => $instituto["#options"],
		//'#parents' => array('publicador'),
	);
		
	$instituto = taxonomy_form(9);
	$form['taxonomy[9]'] = array(
    	'#type' => 'select', 
    	'#title' => t($instituto["#title"]), 
    	'#default_value' => $instituto["#default_value"], 
    	'#options' => $instituto["#options"],
		//'#parents' => array('publicador'),
	);
		
	$instituto = taxonomy_form(8);
	$form['taxonomy[8]'] = array(
    	'#type' => 'select', 
    	'#title' => t($instituto["#title"]), 
    	'#default_value' => $instituto["#default_value"], 
    	'#options' => $instituto["#options"],
		//'#parents' => array('publicador'),
	);
		
	$instituto = taxonomy_form(10);
	$form['taxonomy[10]'] = array(
    	'#type' => 'select', 
    	'#title' => t($instituto["#title"]), 
    	'#default_value' => $instituto["#default_value"], 
    	'#options' => $instituto["#options"],
		//'#parents' => array('publicador'),
	);
	
	/*$form['taxonomy1'] = array(
		taxonomy_form(9),
		taxonomy_form(5),
		taxonomy_form(4),
		taxonomy_form(8),
		taxonomy_form(7),
		taxonomy_form(3),
		taxonomy_form(10),
	);*/
	$form['submit'] = array(
		'#type'  => 'submit',
		'#value' => 'Grabar',
		);
	return $form;
}

function custom_p_educacion_form_submit($form_id, $form) {
	global $user;
	$form_id = 'p-educacion_node_form';
	$node = array(
		'uid'  => $user->uid,
		'name' => $user->name,
		'type' => 'p-educacion',
	);
	$form_values = array(
		'title'    => $form['title'],
		'name'     => $user->name,
		'taxonomy' => $form['taxonomy'],
	);
	watchdog('debug', 'Saving foo from mini node form');
	drupal_execute($form_id, $form_values, $node);
} 