<?php 
/**
 * views template to output one 'row' of a view.
 * This code was generated by the views theming wizard
 * Date: Mon, 08/03/2010 - 16:25
 * View: mi_educacion
 *
 * Variables available:
 * $view -- the entire view object. Important parts of this object are
 *   mi_educacion, .
 * $view_type -- The type of the view. Probably 'page' or 'block' but could
 *   also be 'embed' or other string passed in from a custom view creator.
 * $node -- the raw data. This is not a real node object, but will contain
 *   the nid as well as other support fields that might be necessary.
 * $count -- the current row in the view (not TOTAL but for this page) starting
 *   from 0.
 * $stripe -- 'odd' or 'even', alternating. * $title -- Display the title of the node.
 * $title_label -- The assigned label for $title
 * $created -- Display the post time of the node. The option field may be used to specify the custom date format as it's required by the date() function or if "as time ago" has been chosen to customize the granularity of the time interval.
 * $created_label -- The assigned label for $created
 * $view -- Display a link to view the node. Enter the text of this link into the option field; if blank the default "View" will be used.
 * $view_label -- The assigned label for $view
 * $edit -- Display a link to edit the node. Enter the text of this link into the option field; if blank the default "Edit" will be used.
 * $edit_label -- The assigned label for $edit
 * $delete -- Display a link to delete the node. Enter the text of this link into the option field; if blank the default "Delete" will be used.
 * $delete_label -- The assigned label for $delete
 *
 * This function goes in your views-list-mi_educacion.tpl.php file
 */
 
 
 //now we add the stylesheet...
  drupal_add_css(path_to_theme() .'/views-list-mi_educacion.css');
  ?>
<div class="view-label view-field-title">
  <?php print $title_label ?>
</div>
<div class="view-field view-data-title">
  <?php print $title?>
</div>

<div class="view-label view-field-created">
  <?php print $created_label ?>
</div>
<div class="view-field view-data-created">
  <?php print $created?>
</div>

<div class="view-label view-field-view">
  <?php print $view_label ?>
</div>
<div class="view-field view-data-view">
  <?php print $view?>
</div>

<div class="view-label view-field-edit">
  <?php print $edit_label ?>
</div>
<div class="view-field view-data-edit">
  <?php print $edit?>
</div>

<div class="view-label view-field-delete">
  <?php print $delete_label ?>
</div>
<div class="view-field view-data-delete">
  <?php print $delete?>
</div>
??????

