<?php
// $Id: empleos.module,v 1.0 2009/10/01 09:00:00 Francisco Piantoni Exp $

define('EMPLEOS_PERM_ADMINISTER',  'administer empleos');
define('EMPLEOS_PAGE_LIMIT',       'empleos_page_limit');
define('EMPLEOS_PAGE_TYPE',        'empleos_page_type');
define('EMPLEOS_VIEW_NEWS_PROFILE','empleos_view_news_profile');
define('EMPLEOS_BANNER_VIEW',	   'empleos_banner_view');
define('EMPLEOS_LOGO',	           'empleos_logo');


function empleos_cron() {
	
	// actualizo las variables de avisos y empresas para la home 
   $base_query = "SELECT count(*) FROM {node} AS n  ";
   $inner_join = "INNER JOIN {content_type_e_aviso} AS w ON w.nid = n.nid ";
   $where      = "WHERE n.type = 'e_aviso' AND n.status = 1 ";
	
   $sql = $base_query.$inner_join.$where;
   $avisos_count = db_result(db_query($sql));
   
   //$base_query = "SELECT count(*) FROM {node} AS n  ";
   //$inner_join = "INNER JOIN {content_type_e_aviso} AS w ON w.nid = n.nid ";
   //$where      = "WHERE n.type = 'e_aviso' AND w.field_fecha_desde_value >= now() - 30";

   //$sql = $base_query.$inner_join.$where;
   //$avisos_recientes = db_result(db_query($sql));
   $avisos_recientes = 123;

   $base_query = "SELECT count(*) FROM {users} AS u ";
   $inner_join = "INNER JOIN {users_roles} AS ur ON ur.uid = u.uid ";
   $where      = "WHERE STATUS = 1 AND ur.rid = 5";

   $sql = $base_query.$inner_join.$where;
   $empresas_count = db_result(db_query($sql));
   
   Variable_set('avisos_count',$avisos_count);
   Variable_set('empresas_count',$empresas_count);
   Variable_set('empresas_recientes',$empresas_count);   
}

function empleos_menu($may_cache) {
  $items = array();

  if ($may_cache) {
	$items[] = array(
      'title'              => 'Empleos',
      'path'               => 'admin/settings/empleos',
      'description'        => 'Settings for Empleos',
      'callback'           => 'drupal_get_form',
      'callback arguments' => 'empleos_settings',
      'type'               => MENU_NORMAL_ITEM,
      'access'             => user_access(EMPLEOS_PERM_ADMINISTER)
    );
	
	$items[] = array(
	  'title'    			=> 'Buscador',
      'path'     			=> 'buscar',
      'callback' 			=> 'empleos_buscar',
      'type' 				=> MENU_CALLBACK,	  
	  'access'   			=> TRUE,
	  'weight' => 100
    );
	
	
	$items[] = array(
	  'title'    			=> 'Rubros',
      'path'     			=> 'rubro',
      'callback' 			=> 'empleos_rubro',
      'type' 				=> MENU_CALLBACK,	  
	  'access'   			=> TRUE,
	  'weight' => 100
    );
	
	
	$items[] = array(
	  'title'    			=> 'Consultoras',
      'path'     			=> 'consultora',
      'callback' 			=> 'empleos_consultora',
      'type' 				=> MENU_CALLBACK,	  
	  'access'   			=> TRUE,
	  'weight' => 100
    );
	
	$items[] = array(
	  'title'    			=> 'Universidades',
      'path'     			=> 'universidad',
      'callback' 			=> 'empleos_universidad',
      'type' 				=> MENU_CALLBACK,	  
	  'access'   			=> TRUE,
	  'weight' => 100
    );
		
	
	$items[] = array(
	  'title'    			=> 'Empresas',
      'path'     			=> 'empresa',
      'callback' 			=> 'empleos_empresa',
      'type' 				=> MENU_CALLBACK,	  
	  'access'   			=> TRUE,
	  'weight' => 100
    );

	$items[] = array(
	  'title'    			=> 'Sector',
      'path'     			=> 'sector',
      'callback' 			=> 'empleos_sector',
      'type' 				=> MENU_CALLBACK,	  
	  'access'   			=> TRUE,
	  'weight' => 100
    );

	$items[] = array(
	  'title'    			=> 'Provincia',
      'path'     			=> 'provincia',
      'callback' 			=> 'empleos_provincia',
      'type' 				=> MENU_CALLBACK,	  
	  'access'   			=> TRUE,
	  'weight' => 100
    );
	
	$items[] = array(
	  'title'    			=> 'Nota',
      'path'     			=> 'nota',
      'callback' 			=> 'empleos_nota',
      'type' 				=> MENU_CALLBACK,	  
	  'access'   			=> TRUE,
	  'weight' => 100
    );

	$items[] = array(
	  'title'    			=> 'Novedades',
      'path'     			=> 'novedades',
      'callback' 			=> 'empleos_novedades',
      'type' 				=> MENU_CALLBACK,	  
	  'access'   			=> TRUE,
	  'weight' => 100
    );
	
	$items[] = array(
	  'title'    			=> 'Busqueda avanzada',
      'path'     			=> 'avanzada',
      'callback' 			=> 'empleos_avanzada',
      'type' 				=> MENU_CALLBACK,	  
	  'access'   			=> TRUE,
	  'weight' => 100
    );
	
	$items[] = array(
	  'title'    			=> 'Mapa del sitio',
      'path'     			=> 'mapadelsitio',
      'callback' 			=> 'empleos_mapadelsitio',
	  'access'   			=> TRUE,
	  'type' 				=> MENU_CALLBACK,
	  'weight' 				=> 100
    );
	
   $items[] = array(
      'path' 				=> 'empleos/stat',
      'access' 				=> TRUE,
      'type' 				=> MENU_CALLBACK,
      'callback' 			=> 'empleos_getstat'
     );
	
	}
	
  return $items;
}



function empleos_getstat() {
	// actualizar las estadisticas
	db_query('INSERT INTO {empleos_stat} (uid, what, oid, created) VALUES (%d, "%s", %d, %d)', arg(3),arg(2), arg(4), time() );
	switch (arg(2)) {
		case 'aviso':
		   // actualizo la cantidad de veces que lo vieron
		   	db_query('UPDATE {content_type_e_aviso} SET field_visitas_value = field_visitas_value + 1 WHERE nid=%d', arg(4));
			print '[UPDATE {content_type_e_aviso} SET field_visitas_value = field_visitas_value + 1 WHERE nid='.arg(4).']';
	}
	// habilitar las dos lineas de abajo para debuguear	
	$output = '[?='.arg(2).'][q='.arg(3).'][a='.arg(4).']';
	echo $output;
}

function empleos_test() {
   return '';
}

function empleos_buscar() { 
   return '';
}

function empleos_rubro() {
   return '';
}

function empleos_provincia() {
   return '';
}

function empleos_sector() {
   return '';
}

function empleos_empresa() {
   return '';
}

function empleos_consultora() {
   return '';
}
function empleos_universidad() {
   return '';
}
function empleos_mapadelsitio() {
   return '';
}
function empleos_avanzada() {
   return '';
}
function empleos_nota() {
   return '';
}

function empleos_novedades() {
   return '';
}

function empleos_settings() {
  $set = 'page';
  $form[$set] = array(
    '#type' => 'fieldset',
    '#title' => t('Empleos Page Settings'),
    '#collapsible' => true,
    '#collapsed' => false,
  );
  $form[$set][EMPLEOS_PAGE_LIMIT] = array(
    '#type' => 'textfield',
    '#title' => t('Empleos Page Limit'),
    '#default_value' => variable_get(EMPLEOS_PAGE_LIMIT, 10),
    '#description' => t('Cuantos items se muestran por pagina de resultados de busquedas.'),
  );
  $form[$set][EMPLEOS_BANNER_VIEW] = array(
    '#type' => 'textfield',
    '#title' => t('Banners en Resultados de Busqueda'),
    '#default_value' => variable_get(EMPLEOS_BANNER_VIEW, 10),
    '#description' => t('Cuantos banners se muestran por pagina de resultados de busquedas.'),
  );

  $form[$set][EMPLEOS_VIEW_NEWS_PROFILE] = array(
    '#type' => 'checkbox',
    '#title' => t('Ver novedades en el profile'),
    '#default_value' => variable_get(EMPLEOS_VIEW_NEWS_PROFILE, 1),
    '#description' => t('Muestra las novedades en el profile de los usuarios registrados.'),
  );
  

  $set = 'types';
  $form[$set] = array(
    '#type' => 'fieldset',
    '#title' => t('Indexar estos tipos de nodos'),
    '#collapsible' => true,
    '#collapsed' => false,
  );
  foreach (_node_types_natcasesort() as $type) {
    $form[$set][EMPLEOS_PAGE_TYPE . $type->type] = array(
      '#type' => 'checkbox',
      '#title' => $type->name,
      '#return_value' => 1,
      '#default_value' => variable_get(EMPLEOS_PAGE_TYPE . $type->type, 0),
    );
  }

  return system_settings_form($form);
}

