<?php
// $Id: sphinx.module,v 1.2.2.1 2008/09/25 19:26:19 johsw Exp $


/**
 * @file
 * Sphinx module
 *
 * This module interfaces Sphinxsearch with Drupal (http://www.sphinxsearch.com)
 *
 *  The module is made by Johs. Wehner (http://drupal.org/user/58666)
 * The module is sponsored by Dagbladet Information (http://www.information.dk)
 */


$path = './'. drupal_get_path('module', 'sphinx') .'/includes/api';
$api_file = $path .'/sphinxapi.php';
if (file_exists($api_file)) {
  include_once($api_file);
}
require ('./'. drupal_get_path('module', 'sphinx') .'/sphinx_admin.inc.php');

/**
 * Implementation of hook_menu().
 */
function sphinx_menu() {
  if (!$may_cache) {
    $items[] = array(
      'path' => 'admin/settings/sphinx',
      'title' => t('Sphinx settings'),
      'description' => t('Configure the Sphinx search and result pages'),
      'callback' => '_sphinx_admin',
      'access' => user_access('administer sphinx search'),
      'type' => MENU_NORMAL_ITEM,
    );
    $items[] = array(
      'path' => 'admin/settings/sphinx/main',
      'title' => t('Sphinx settings'),
      'description' => t('Configure the Sphinx search and result pages'),
      'callback' => '_sphinx_admin',
      'access' => user_access('administer sphinx search'),
      'weight' => -1,
      'type' => MENU_DEFAULT_LOCAL_TASK,
    );
    
    $items[] = array(
      'path' => 'admin/settings/sphinx/indexes',
      'title' => t('Indexes'),
      'description' => t('Configure the Sphinx indexes'),
      'callback' => '_sphinx_admin_indexes',
      'access' => user_access('administer sphinx search'),
      'type' => MENU_LOCAL_TASK,
    );
    $items[] = array(
      'path' => 'admin/settings/sphinx/fields',
      'title' => t('Fields'),
      'description' => t('Configure the Sphinx fields'),
      'callback' => '_sphinx_alter_fields',
      'access' => user_access('administer sphinx search'),
      'type' => MENU_CALLBACK,
    );
    $items[] = array(
      'path' => 'admin/settings/sphinx/attributes',
      'title' => t('Attributes'),
      'description' => t('Configure the Sphinx attributes'),
      'callback' => '_sphinx_alter_attributes',
      'access' => user_access('administer sphinx search'),
      'type' => MENU_CALLBACK,
    );
    
    $default = _sphinx_get_path_by_iid(variable_get('sphinx_default_index', ''));
    if(!empty($default)) {
      $items[] = array(
        'path' => 'search',
        'title' => utf8_encode('Search'),
        'description' => t('Search'),
        'callback' => 'drupal_goto',
        'callback arguments' => array('search/'.$default),
        'access' => user_access('use sphinx search'),
        'type' => MENU_NORMAL_ITEM,
      );
    }
    $res = db_query('SELECT iid, display_name, path FROM {sphinx_indexes} WHERE active=1');
    while ($indexes = db_fetch_object($res)) {
      $items[] = array(
        'path' => 'search/'. $indexes->path,
        'title' => t('Search !index', array('!index' => $indexes->display_name)),
        'description' => t('Search !index', array('!index' => $indexes->display_name)),
        'callback' => '_sphinx_search_page',
        'callback arguments' => array(arg(1), arg(2)),
        'access' => user_access('use index '. $indexes->display_name .'('. $indexes->iid .')'),
        'type' => MENU_LOCAL_TASK,
      );
    }
  }
  return $items;
}

/**
 * Implementation of hook_perm().
 */
function sphinx_perm() {
  $permissions = array('use sphinx search', 'administer sphinx search');
  $res = db_query('SELECT iid, display_name, path FROM {sphinx_indexes} WHERE active=1');
  while ($indexes = db_fetch_object($res)) {
  	$permissions[] = 'use index '. $indexes->display_name .'('. $indexes->iid .')';
  }
  return $permissions;
}

/**
 * Implementation of hook_help().
 */
function sphinx_help($section = '') {
  $output = '';
  switch ($section) {
    case 'admin/help#infsphinxphpsearch':
      $output = '<p>'. t('Sphinx search (Dagbladet Information)') .'</p>';
      break;
  }
  return $output;
}

function _sphinx_get_index_by_path($path = null) {
  if (!empty($path)) {
    $res = db_query('SELECT iid FROM {sphinx_indexes} WHERE path="%s"', $path);
    $index = db_fetch_object($res);
    return $index->iid;
  }
}

function _sphinx_get_index_by_name($path = null) {
  if (!empty($path)) {
    $res = db_query('SELECT iid FROM {sphinx_indexes} WHERE index_name="%s"', $path);
    $index = db_fetch_object($res);
    return $index->iid;
  }
}

function _sphinx_get_path_by_iid($iid = null) {
  if (!empty($iid)) {
    $res = db_query('SELECT path FROM {sphinx_indexes} WHERE iid=%d', $iid);
    $index = db_fetch_object($res);
    return $index->path;
  }
}

function _sphinx_get_attr_by_aid($aid = null) {
  if (!empty($aid)) {
    $res = db_query('SELECT attribute_name FROM {sphinx_attributes} WHERE aid=%d', $aid);
    $index = db_fetch_object($res);
    return $index->attribute_name;
  }
}

function _sphinx_get_active_fields_by_iid($iid = null) {
  if (!empty($iid)) {
    $output = array();
    $res = db_query('SELECT fid, field_name FROM {sphinx_fields} WHERE iid=%d && active=1', $iid);
    while ($fields = db_fetch_object($res)) {
      $output[$fields->fid] = $fields->field_name;
    }
    return $output;
  }
}

/**
 * The search page callback
 */
function _sphinx_search_page($index_name, $needle = null) {
  
  drupal_add_css(drupal_get_path('module', 'sphinx') .'/sphinx.css');
  $iid    = _sphinx_get_index_by_path($index_name);
  $output = drupal_get_form('sphinx_search_form', $iid, $needle);
  $sql    = 'SELECT {sphinx_indexes}.*, {sphinx_attributes}.attribute_name AS sort_field FROM {sphinx_indexes} LEFT JOIN {sphinx_attributes} ON default_sort_key_fid = aid WHERE {sphinx_indexes}.iid=%d';
  
  $res    = db_query($sql, $iid);
  $index  = db_fetch_object($res);
  $client = new SphinxClient();
  $connect = $client->_Connect();
  if (!$connect) {
    drupal_set_message(variable_get('sphinx_offline_message', ''));
    return;
  }
  if (!empty($_GET['as_sk'])) {
    $sort = _sphinx_get_attr_by_aid($_GET['as_sk']);
  }
  else if (!empty($index->sort_field)) {
    $sort = $index->sort_field;
  }
  else {
    $sort = '';
  }
  if (!empty($sort)) {
    if (!empty($_GET['as_sd'])) {
      $order = ($_GET['as_sd'] == 'asc') ? 'asc' : 'desc';
    }
    elseif (!empty($index->default_sort_order)) {
      $order = $index->default_sort_order;
    }
    else {
      $order = 'desc';
    }
  }
  $fields = _sphinx_get_active_fields_by_iid($iid);
  
  foreach ($fields as $fid => $name) {
    $term = $_GET['as_f'. $fid];
    if (!empty($term)) {
      $needle .= '@'. $name .' '. $term .' ';
    }
  }
  if (!empty($_GET['as_filter'])) {
    $filter_codes = explode('-', $_GET['as_filter']);
    $filters = array();
    for($z=0; $z<count($filter_codes); $z++){
      $parts = explode('_',$filter_codes[$z]);
      
      if(!empty($parts[0]) && !empty($parts[1])) {
        $attr =  _sphinx_get_attr_by_aid($parts[0]);
        if(array_key_exists($attr, $filters)){
          $filters[$attr][] = $parts[1];
        } else {
          $filters[$attr] = array($parts[1]);
        }
      }
    }
  }
  if (!empty($needle)) {
    if (isset($_GET['pr_page'])) {
      $limit = (int)$_GET['pr_page'];
    }
    else {
      $limit = variable_get('sphinx_results_per_page', '10');
    }
    $results = _sphinx_do_search($client, $needle, $index->index_name, $sort, $order, $filters, $limit);
    $output .= theme_sphinx_results($results[0], $index->index_name, $needle, $index->excerpt);
    $output .= _sphinx_pager($results[0], $limit);
  }
  return $output;
}

/**
 * Do the search
 *
 *
 * @param $client
 *   A SphinxClient Object
 * @param $needle
 *   A string containing the word(s) to search for
 * @param $index
 *   A string constaining the index(es) to search
 * @param $sort
 *   A string constaining instructions for the sorting of results
 *
 * @return
 *   true if the address is in a valid format.
 */
function _sphinx_do_search($client, $needle, $index, $sort, $order, $filters = null, $limit) {
  if (!empty($sort)) {
    $client->SetSortMode(SPH_SORT_EXTENDED, $sort.' '.$order);
  } else {
    $client->SetSortMode(SPH_SORT_RELEVANCE);
  }
  if(is_array($filters)){
    foreach($filters as $attribute => $values){
      for($x=0; $x<count($values); $x++){
      	$client->SetFilter( $attribute, array($values[$x]));
      }
    }
  }
  $client->SetMatchMode(SPH_MATCH_EXTENDED);
  if (isset($_GET['page'])) {
    $offset = (int)($_GET['page'] * $limit);
    $client->SetLimits($offset, intval($limit));
  }
  else {
    $client->SetLimits(0, intval($limit));
  }
  $client->AddQuery($needle, $index);
  $response = $client->RunQueries();
  
  return $response;
}

/**
 * Render the search results
 *
 *
 * @param $results
 *   An array returned by the Sphinx api
 * @param $needle
 *   A string containing the word(s) to search for
 *
 * @return
 *   true if the address is in a valid format.
 */
function theme_sphinx_results($results, $index, $needle, $show_excerpts) {
  $client = new SphinxClient();
  $output = '';
  $output .= theme_sphinx_feedback($results, $needle);
  if ($results['total_found'] > 0) {
    $lines = array();
    foreach ($results['matches'] as $k => $v) {
      $node = node_load($k);
      if ($node->nid) {
        if ($show_excerpts) {
          $fields = _sphinx_excerpt_fields($index);
          //$content = _sphinx_excerpt_content($index, $node);
          //TODO: need to figure out how db-fields are translated to arrays in order to retrieve the relevant fields
          $excerpt = $client->BuildExcerpts(array($node->title, $node->field_brdtekst), $index, $needle, $opts = array());
          //print_r($fields);	
          $lines[] = theme_sphinx_result($node, $excerpt, $fields);
        }
        else {
          $lines[] = theme_sphinx_result($node);
        }
      }
    }
  }
  $output = theme('item_list', $lines);
  return $output;
}

function theme_sphinx_feedback($results, $needle) {
  $output = '';
  $output .= '<div class="sphinx-search-feedback">';
  $output .= $results['total_found'] .' ';
  $output .= ($results['total_found'] == 1) ? t('result') : t('results');
  $output .= ' '. t('for');
  $output .= '<span class="sphinx-search-term"> '. $needle .'</span>  ('. $results['time'] .' '. t('secs.') .')';
  $output .= '</div>';
  return $output;
}

function theme_sphinx_result($node, $excerpt = null, $fields = null) {
  if (is_array($excerpt)) {
    return theme_sphinx_excerpt_result($node, $excerpt, $fields);
  }
  else {
    return node_view($node, true);
  }
}

function theme_sphinx_excerpt_result($node, $excerpt, $fields) {
  $output = '';
  if (is_array($excerpt)) {
    $output .= '<div class="sphinx-field-'. $fields[0] .'">'. l($excerpt[0], 'node/'. $node->nid, array(), null, null, false, true) .'</div>';
    for ($n = 1; $n < count($excerpt); $n++) {
      $output .= '<div class="sphinx-field-'. $fields[$n] .'">'. $excerpt[$n] .'</div>';
    }
  }
  return $output;
}

function _sphinx_pager($results, $limit) {
  if ($results['total'] > 0) {
    global $pager_total_items, $pager_total, $pager_page_array;
    $pager_total_items[0] = (int) $results['total'];
    $pager_total[0] = ceil($results['total'] / $limit);
    $pager_page_array[0] = max(0, min((int) $_GET['page'], ($pager_total[0] - 1)));
  }
  $output = theme('pager');
  return $output;
}

/**
 * FAPI definition for the sphinx search form.
 *
 * ...
 * @ingroup forms
 * @see sphinx_search_form_validate()
 * @see sphinx_search_form_submit()
 */
function sphinx_search_form($iid, $needle) {
  
  $sql = 'SELECT * FROM {sphinx_indexes} WHERE iid=%d AND active=1';
  $result = db_query($sql, $iid);
  $index = db_fetch_object($result);
  /*$form['sphinx_search']['index'] = array(
    '#value' => t('Search for !display_name', array('!display_name' => $index->display_name)),
				'#weight' => -10,
  );*/
  $form['sphinx_search']['index_path'] = array(
    '#type' => 'hidden',
    '#value' => $index->path,
		);
  $form['sphinx_search']['iid'] = array(
    '#type' => 'hidden',
    '#value' => $iid,
  );
  $form['sphinx_search']['searchstring'] = array(
    '#type' => 'textfield',
    '#default_value' => $needle,
    '#size' => 60,
    '#maxlength' => 128,
    '#required' => false,
				'#weight' => -8,
  );
  $form['sphinx_search']['advanced'] = array(
    '#type' => 'fieldset',
    '#title' => t('Advanced search'),
    '#collapsible' => true,
    '#collapsed' => ($_GET['as'] == 1) ? false : true,
				'#weight' => -6,
  );
  
  $sql     = 'SELECT aid, attribute_name, display_name FROM {sphinx_attributes} WHERE iid=%d AND active=1';
  $result  = db_query($sql, $iid);
  $options = array(0 => '');
  while ($attributes = db_fetch_object($result)) {
    
    $options[$attributes->aid] = $attributes->display_name;
  }
  $sql = 'SELECT fid, field_name, display_name FROM {sphinx_fields} WHERE iid=%d AND active=1 ORDER BY weight';
  $result = db_query($sql, $iid);
		$count = -40;
  while ($fields = db_fetch_object($result)) {
    
    $form['sphinx_search']['advanced']['field'][$fields->field_name] = array(
      '#title' => $fields->display_name,
      '#type' => 'textfield',
      '#default_value' => (!empty($_GET['as_f'. $fields->fid])) ? $_GET['as_f'. $fields->fid] : '',
      '#required' => false,
						'#weight' => $count,
    );
				$count+=2;
  }
  $form['sphinx_search']['advanced']['sort_key'] = array(
    '#type' => 'select',
    '#title' => t('Sort'),
    '#options' => $options,
    '#default_value' => (!empty($_GET['as_sk'])) ? $_GET['as_sk'] : '',
				'#weight' => 50,
    //'#description' => t('Select what you want to order by'),
  );
  $form['sphinx_search']['advanced']['sort_direction'] = array(
    '#type' => 'select',
    '#title' => t('Order'),
    '#options' => array('asc' => t('Ascending'), 'desc' => t('Descending')),
    '#default_value' => (!empty($_GET['as_sd'])) ? $_GET['as_sd'] : '',
				'#weight' => 60,
  );
  
  $form['sphinx_search']['submit'] = array('#type' => 'submit', '#value' => t('Search'), '#weight' => 2,);
  
  
  return $form;
}

function sphinx_search_form_validate($form_id, $form_values) {
  $search = $form_values['searchstring'];
  $sql    = 'SELECT fid,field_name FROM {sphinx_fields} WHERE iid=%d AND active=1 ORDER BY weight DESC';
  $res    = db_query($sql, $form_values['iid']);
  while ($fields = db_fetch_object($res)) {
    $field = $form_values[$fields->field_name];
    if (!empty($field)) {
      $search .= $field;
    }
  }
  if (empty($search)) {
    form_set_error($form_values['searchstring'], t('You must enter a search string'));
  }
}

function sphinx_search_form_submit($form_id, $form_values) {
  $query = _sphinx_build_advanced_query($form_values);
  drupal_goto('search/'. $form_values['index_path'] .'/'. $form_values['searchstring'], $query);
}

function _sphinx_build_advanced_query($form_values) {
  $output = '';
  $sql    = 'SELECT fid,field_name FROM {sphinx_fields} WHERE iid=%d AND active=1 ORDER BY weight DESC';
  $res    = db_query($sql, $form_values['iid']);
  while ($fields = db_fetch_object($res)) {
    $field = $form_values[$fields->field_name];
    if (!empty($field)) {
      $output .= 'as_f'. $fields->fid .'='. $field .'&';
    }
  }
  if ($form_values['sort_key']) {
    $output .= 'as_sk='. $form_values['sort_key'] .'&as_sd='. $form_values['sort_direction'] .'&';
  }
  if (!empty($output)) {
    return 'as=1&'. substr($output, 0, -1);
  }
  else {
    return null;
  }
}

function _sphinx_excerpt_fields($index) {
  $output = array();
  $sql    = 'SELECT field_name FROM {sphinx_fields} WHERE iid=%d AND excerpt=1 ORDER BY weight DESC';
  $res    = db_query($sql, _sphinx_get_index_by_name($index));
  while ($fields = db_fetch_object($res)) {
    $output[] = strtolower($fields->field_name);
  }
  return $output;
}

