<?php
// $Id: multistep.install,v 1.1.2.1 2009/03/07 19:54:42 vkareh Exp $

function multistep_install() {
  // Clear cache to take into account the change in forms immediately.
  cache_clear_all('content_type_info', 'cache_content');
}

function multistep_uninstall() {
  // Clear cache to take into account the change in forms immediately.
  cache_clear_all('content_type_info', 'cache_content');
}
