<?php
// $Id: publicador.module,v 1.3.4.5 2009/03/31 02:30:17 cdale Exp $

/**
* Display help and module information
* @param section which section of the site we're displaying help 
* @return help text for section
*/
function publicador_help($section='') {
  $output = '';
  switch ($section) {
    case "admin/help#publicador":
      $output = '<p>'.  t("Displays links to nodes created on this date"). '</p>';
      break;
  }
  return $output;
}

function publicador_menu($may_cache) {
  global $user;
	$nid = arg(1);
  $items = array();
  if ($may_cache) {
    $items[] = array(
      'path' => 'admin/publicador',
      'title' => t('Publicador'),
      'callback' => 'publicador_admin_content',
      'access' => user_access('access publicador'),
      'description' => t('View and edit all the available publicadors on your site.'),
      'type' => MENU_NORMAL_ITEM,
    );
    return $items;
  }elseif(arg(0) == 'publicador' && is_numeric(arg(1))){
      $items[] = array(
        'path' => 'publicador/'. $nid ,
        'title' => t('Publicar mis avisos paso 2'),
        'callback' => 'publicador_node',
        'callback arguments' => array($nid),
        'access' => user_access('access publicador results') || user_access('access publicador submissions') || (user_access('access own publicador submissions')  && $user->uid),
        'weight' => 2,
        'type' => MENU_CALLBACK,
      );
      return $items;
  }elseif (arg(0) == 'publicador') {
      /* MRAD */
      $items[] = array(
        'path' => 'publicador',
        'title' => t('Publicar mis avisos'),
        'callback' => 'publicador',
        'callback arguments' => array($user, 'user_submissions'),
        'access' => user_access('access publicador results') || user_access('access publicador submissions') || (user_access('access own publicador submissions')  && $user->uid),
        'weight' => 2,
        'type' => MENU_CALLBACK,
      );
	return $items;
	}elseif(arg(0) == "admin" && arg(1) == "publicador" && arg(2) == "code"){
      $items[] = array(
        'path' => 'admin/publicador/code',
        'title' => t('Administracion de codigos de publicacion'),
        'callback' => 'publicador_code_list',
        'callback arguments' => array($user, 'user_submissions'),
        'access' => user_access('access publicador results') || user_access('access publicador submissions') || (user_access('access own publicador submissions')  && $user->uid),
        'weight' => 2,
        'type' => MENU_CALLBACK,
      );
      return $items;
	}elseif(arg(0) == "admin" && arg(1) == "publicador" && arg(2) == "generar"){
      $items[] = array(
        'path' => 'admin/publicador/generar',
        'title' => t('Generacion de codigos de publicacion'),
        'callback' => 'publicador_code_generator',
        'callback arguments' => array($user, 'user_submissions'),
        'access' => user_access('access publicador results') || user_access('access publicador submissions') || (user_access('access own publicador submissions')  && $user->uid),
        'weight' => 2,
        'type' => MENU_CALLBACK,
      );
      return $items;
	}elseif(arg(0) == "admin" && arg(1) == "publicador" && arg(2) == "asociar"){
      $items[] = array(
        'path' => 'admin/publicador/asociar',
        'title' => t('Asignar codigo a usuario'),
        'callback' => 'publicador_code_asociar',
        'callback arguments' => array($user, 'user_submissions'),
        'access' => user_access('access publicador results') || user_access('access publicador submissions') || (user_access('access own publicador submissions')  && $user->uid),
        'weight' => 2,
        'type' => MENU_CALLBACK,
      );
      return $items;
	}
}

function publicador($user){
	$sql = "SELECT * FROM node AS n WHERE n.status = 1 AND n.type = 'e_aviso' AND n.uid = 5 ORDER BY created DESC ";
	$rs = db_query($sql);
	$i = 0;
	while ($aviso = mysql_fetch_object($rs)) {
		$row[] = "<b>".$i."</b>";
		$row[] = "<a href='?q=node/".$aviso->nid."'>".$aviso->title."</a>";
		$row[] = "<a href='?q=publicador/".$aviso->nid."'>Publicar</a>";
		$rows[] = $row;
		unset($row);
		$i++;
	}
  $header = array(t('#'),t('Aviso'), t('Publicar'));

  // Create the table inside the form.
  $form['components']['table'] = array(
    '#value' => theme('table', $header, $rows)
  );

  $output = drupal_render($form);
  return $output;
}

function publicador_node($nid){
  // Create the table inside the form.
  
  $form['publicador']['publicar'] = array(
    '#type' => 'fieldset',
    '#title' => t('Programar Publicacion'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
    '#weight' => -4,
    '#parents' => array('publicador'),
  );
  
  $form['publicador']['publicar']['desde'] = array(
    '#type' => 'textfield',
    '#title' => t('Desde'),
    '#default_value' => date("Y-m-d"),
    '#maxlength' => 10,
    '#required' => TRUE,
    '#tree' => FALSE,
  );
  
  $form['publicador']['publicar']['hasta'] = array(
    '#type' => 'textfield',
    '#title' => t('Hasta'),
    '#default_value' => date("Y-m-d"),
    '#maxlength' => 10,
    '#required' => TRUE,
    '#tree' => FALSE,
  );
  
	$row[] = "<a href='?q=publicador'>anterior</a>";
	$row[] = "<a href='?q=publicador/".$nid."/formas'>Siguiente</a>";
	$rows[] = $row;
	$header = array(t('Navegador'));

  // Create the table inside the form.
  $form['components']['table'] = array(
    '#value' => theme('table', $header, $rows)
  );

  
  $output = drupal_render($form);
  return $output;
}

function publicador_code_list(){
	$sql = "SELECT * FROM pub_codigos  AS pc INNER JOIN pub_tipo AS pt ON pc.tid = pt.tid WHERE pc.dias_restantes > 0 ORDER BY pc.cid DESC";
	$rs = db_query($sql);
	if(mysql_num_rows($rs)>0){
		$i = 0;
		while ($codigo = mysql_fetch_object($rs)) {
			$empresa = user_load(array("uid" => $codigo->uid));
			$row[] = "<b>".$i."</b>";
			$row[] = $codigo->codigo;
			$row[] = $codigo->name;
			$row[] = "<a href='?q=user/".$empresa->uid."'>".$empresa->name."</a>";
			$rows[] = $row;
			unset($row);
			$i++;
		}	
	}
	
	$row[] = "";
	$row[] = "";
	$row[] = "";
	$row[] = "<a href='?q=admin/publicador/generar'>Generar Codigo</a>";
	$rows[] = $row;
	$header = array(t('#'),t('Codigo'), t('Tipo'), t('Usuario'));

  // Create the table inside the form.
  $form['components']['table'] = array(
    '#value' => theme('table', $header, $rows)
  );

  $output = drupal_render($form);
  return $output;
}

function publicador_code_generator(){
	$codigo = "";
	$longitud = 10;
	for ($i=1; $i<=$longitud; $i++){
		$letra = chr(rand(97,122));
		$codigo .= $letra;
	}
	$codigo = strtoupper($codigo);
	$sql = "SELECT * FROM pub_codigos WHERE codigo = '$codigo'";
	$rs = db_query($sql);
	if(mysql_num_rows($rs)==0){
		$sql = "INSERT INTO pub_codigos(codigo) VALUES('$codigo')";
		db_query($sql);
		drupal_goto("admin/publicador/asociar/".$codigo);
	}else{
		drupal_goto("admin/publicador/generar");
	}
}

function publicador_code_asociar(){
	$form = array();
  $form['publicador']['asociar'] = array(
    '#type' => 'fieldset',
    '#title' => t('Asociar codigo a un usuario'),
    '#collapsible' => FALSE,
    '#collapsed' => FALSE,
    '#weight' => -4,
    '#parents' => array('publicador'),
  );
  
  $codigo = arg(3);
  
  $form['publicador']['asociar']['codigo'] = array(
    '#type' => 'textfield', 
    '#title' => t('Codigo'), 
    '#value' => t($codigo), 
    '#description' => t('Codigo generado'),
	'#parents' => array('publicador'),
  );
  
  $rs = db_query("select * from pub_tipo where name <> 'gratis'");
  while($fila = mysql_fetch_object($rs)){
  	$tipo[] = $fila->name;
  }
  $form['publicador']['asociar']['tipos'] = array(
    '#type' => 'select', 
    '#title' => t('Tipo de aviso'), 
    '#default_value' => variable_get('timer', 259200), 
    '#options' => $tipo, 
    '#description' => t('Tipos de avisos'),
	'#parents' => array('publicador'),
  );
  
  $form['publicador']['asociar']['periodo'] = array(
    '#type' => 'textfield',
    '#title' => t('Cantidad de dias'),
    '#value' => "30",
    '#maxlength' => 3,
    '#required' => TRUE,
    '#tree' => FALSE,
	'#parents' => array('publicador'),
  );
  
  $form['publicador']['asociar']['usuario'] = array(
    '#type' => 'textfield',
    '#title' => t('usuario'),
    '#required' => TRUE,
    '#tree' => FALSE,
    '#parents' => array('publicador'),
  );
  
  $form['publicador']['submit'] = array(
  	'#type' => 'submit',
  	'#value' => t('Asociar'),
  );

  $output = drupal_render($form);
  return $output;
}

/*function publicador_code_asociar_validate($form_id, $form_values) {
	return true;
}

function publicador_code_asociar_submit($form_id, $form_values) {
	print_r($form_values);
}*/