<?php
// $Id: empleos.module,v 1.0 2009/10/01 09:00:00 Francisco Piantoni Exp $

define('EMPLEOS_PERM_ADMINISTER',  'administer empleos');
define('EMPLEOS_PAGE_LIMIT',       'empleos_page_limit');
define('EMPLEOS_PAGE_TYPE',        'empleos_page_type');
define('EMPLEOS_VIEW_NEWS_PROFILE','empleos_view_news_profile');


function empleos_menu($may_cache) {
  $items = array();

  if ($may_cache) {
	$items[] = array(
      'title'              => 'Empleos',
      'path'               => 'admin/settings/empleos',
      'description'        => 'Settings for Empleos',
      'callback'           => 'drupal_get_form',
      'callback arguments' => 'empleos_settings',
      'type'               => MENU_NORMAL_ITEM,
      'access'             => user_access(EMPLEOS_PERM_ADMINISTER)
    );
	
	$items[] = array(
	  'title'    			=> 'Buscador',
      'path'     			=> 'buscar',
      'callback' 			=> 'empleos_buscar',
	  'access'   			=> TRUE,
	  'weight' => 100
    );
	
	
	$items[] = array(
	  'title'    			=> 'Rubros',
      'path'     			=> 'rubro',
      'callback' 			=> 'empleos_rubro',
	  'access'   			=> TRUE,
	  'weight' => 100
    );
	
	
	$items[] = array(
	  'title'    			=> 'Consultoras',
      'path'     			=> 'consultora',
      'callback' 			=> 'empleos_consultora',
	  'access'   			=> TRUE,
	  'weight' => 100
    );
	
	
	$items[] = array(
	  'title'    			=> 'Empresas',
      'path'     			=> 'empresa',
      'callback' 			=> 'empleos_empresa',
	  'access'   			=> TRUE,
	  'weight' => 100
    );

	$items[] = array(
	  'title'    			=> 'Sector',
      'path'     			=> 'sector',
      'callback' 			=> 'empleos_sector',
	  'access'   			=> TRUE,
	  'weight' => 100
    );

	$items[] = array(
	  'title'    			=> 'Provincia',
      'path'     			=> 'provincia',
      'callback' 			=> 'empleos_provincia',
	  'access'   			=> TRUE,
	  'weight' => 100
    );
	
	$items[] = array(
	  'title'    			=> 'Nota',
      'path'     			=> 'nota',
      'callback' 			=> 'empleos_nota',
	  'access'   			=> TRUE,
	  'weight' => 100
    );
	
	$items[] = array(
	  'title'    			=> 'Busqueda avanzada',
      'path'     			=> 'avanzada',
      'callback' 			=> 'empleos_avanzada',
	  'access'   			=> TRUE,
	  'weight' => 100
    );
	
	$items[] = array(
	  'title'    			=> 'Mapa del sitio',
      'path'     			=> 'mapadelsitio',
      'callback' 			=> 'empleos_mapadelsitio',
	  'access'   			=> TRUE,
	  'weight' => 100
    );
	
	
	}
	
  return $items;
}

function empleos_test() {
   return '';
}

function empleos_buscar() {
   return '';
}

function empleos_rubro() {
   return '';
}

function empleos_provincia() {
   return '';
}

function empleos_sector() {
   return '';
}

function empleos_empresa() {
   return '';
}

function empleos_consultora() {
   return '';
}

function empleos_mapadelsitio() {
   return '';
}
function empleos_avanzada() {
   return '';
}
function empleos_nota() {
   return '';
}


function empleos_settings() {
  $set = 'page';
  $form[$set] = array(
    '#type' => 'fieldset',
    '#title' => t('Empleos Page Settings'),
    '#collapsible' => true,
    '#collapsed' => false,
  );
  $form[$set][EMPLEOS_PAGE_LIMIT] = array(
    '#type' => 'textfield',
    '#title' => t('Empleos Page Limit'),
    '#default_value' => variable_get(EMPLEOS_PAGE_LIMIT, 10),
    '#description' => t('Cuantos items se muestran por pagina de resultados de busquedas.'),
  );
  
  $form[$set][EMPLEOS_VIEW_NEWS_PROFILE] = array(
    '#type' => 'checkbox',
    '#title' => t('Ver novedades en el profile'),
    '#default_value' => variable_get(EMPLEOS_VIEW_NEWS_PROFILE, 1),
    '#description' => t('Muestra las novedades en el profile de los usuarios registrados.'),
  );
  

  $set = 'types';
  $form[$set] = array(
    '#type' => 'fieldset',
    '#title' => t('Indexar estos tipos de nodos'),
    '#collapsible' => true,
    '#collapsed' => false,
  );
  foreach (_node_types_natcasesort() as $type) {
    $form[$set][EMPLEOS_PAGE_TYPE . $type->type] = array(
      '#type' => 'checkbox',
      '#title' => $type->name,
      '#return_value' => 1,
      '#default_value' => variable_get(EMPLEOS_PAGE_TYPE . $type->type, 0),
    );
  }

  return system_settings_form($form);
}

